name: FuzzingwithState
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.22.4
  - gensim
  - transformers=4.41.2
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - scikit-learn
  - nltk
  - pillow
  - aiohttp
  - anyio
  - babel
  - jupyterlab
  - matplotlib-inline
  - pandas
  - requests
  - tqdm
  - typing-extensions
  - typing_extensions
  - zlib
  - pip
  - pip:
      - bert-serving-client
